blank_issues_enabled: false
contact_links:
  - name: pret Discord
    url: https://discord.gg/d5dubZ3
    about: If you need Build Help, Romhack Help, or have General Repo Questions, ask in our discord instead!
