blank_issues_enabled: false
contact_links:
  - name: pret Discord
    url: https://discord.gg/d5dubZ3
    about: If you need help with using pokecrystal, or just have general questions about it, ask in our Discord server!
  - name: Remove Issue Templates
    url: https://github.com/vulcandth/Pret-Test-Issue-Templates/tree/main/.github/ISSUE_TEMPLATE
    about: If this is a downstream repo and you would like to remove these issue templates or modify them, edit/delete the following files
